### ISSUE TITLE
found the issue

### ISSUE THREAD

**Issue by igotinfected** [pegom96/OS_Labs_bash#1]
https://github.com/pegom96/OS_Labs_bash/blob/b8a8cf8ccb4e8725d25a5be93f87326dc31567f1/Lab_7/exercise5.sh#L23

you're not printing the sum here, you're calling the program named 'sum'! That's why your program never stops.
![sum](https://user-images.githubusercontent.com/15004223/34302025-667f3dfa-e72f-11e7-9355-506b99393b10.png)

Replace the three lines where you print the sum with this and it should work: 
`echo "The sum is:$sum"` (remove the parentheses)

**Comment by pegom96** [comment]
Thank you for the help m8 ! It was driving me crazy... How did you notice that anyway ?
